index:
    path: /
    controller: App\Controller\PageController::index

login:
    path: /login
    controller: App\Controller\PageController::login
    
log:
    path: /log
    controller: App\Controller\ActionController::login    